import 'dotenv/config';
import mongoose from 'mongoose';
import User from '../models/User.js';
import { _getLatestTestOtp } from '../services/email.service.js';
import { connectDB } from '../db.js';

const BASE_URL = 'http://localhost:5000/api';

async function runTests() {
  console.log('--- Starting OTP Verification & Profile Gating Tests ---');
  await connectDB();

  // 1. Backfill any existing test users so existing suites don't break
  const backfillResult = await User.updateMany(
    { isVerified: { $exists: false } },
    { $set: { isVerified: true } }
  );
  console.log(`[Backfill] Updated ${backfillResult.modifiedCount} legacy users to isVerified: true`);

  const testEmail = `student_${Date.now()}@studydeck.test`;
  const testPassword = 'SecurePassword123!';

  // 2. Test Registration flow
  console.log(`\n[Test 1] Registering user: ${testEmail}`);
  const regRes = await fetch(`${BASE_URL}/auth/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: testEmail, password: testPassword })
  });
  const regData = await regRes.json();

  console.log('Registration response status:', regRes.status);
  console.log('Registration response body:', regData);

  if (regRes.status !== 201) throw new Error(`Expected 201, got ${regRes.status}`);
  if (regData.requiresVerification !== true) throw new Error('Expected requiresVerification: true');
  if (regData.token) throw new Error('Token should NOT be issued on registration before OTP verification');

  // Verify User document state in MongoDB
  const createdUser = await User.findOne({ email: testEmail });
  if (!createdUser) throw new Error('User not found in MongoDB');
  if (createdUser.isVerified !== false) throw new Error('User.isVerified should be false');
  if (!createdUser.otpHash || !createdUser.otpHash.startsWith('$2')) {
    throw new Error('User.otpHash must be a valid bcrypt hash');
  }
  if (!createdUser.otpExpiresAt) throw new Error('User.otpExpiresAt must be set');
  console.log('✔ MongoDB User verified: isVerified=false, otpHash is bcrypt hashed at rest');

  // 3. Test Login Gating (unverified user must be blocked)
  console.log('\n[Test 2] Attempting login before OTP verification (should be blocked)');
  const unverifiedLoginRes = await fetch(`${BASE_URL}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: testEmail, password: testPassword })
  });
  const unverifiedLoginData = await unverifiedLoginRes.json();

  console.log('Unverified login status:', unverifiedLoginRes.status);
  console.log('Unverified login body:', unverifiedLoginData);

  if (unverifiedLoginRes.status !== 403) throw new Error(`Expected 403 Forbidden, got ${unverifiedLoginRes.status}`);
  if (!unverifiedLoginData.requiresVerification) throw new Error('Expected requiresVerification flag in login response');
  console.log('✔ Login gated: Unverified user received 403 with requiresVerification: true');

  // 4. Test Resend OTP Cooldown (rate limiting)
  console.log('\n[Test 3] Requesting OTP resend immediately (should trigger 60s cooldown 429)');
  const resendCooldownRes = await fetch(`${BASE_URL}/auth/send-otp`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: testEmail })
  });
  const resendCooldownData = await resendCooldownRes.json();

  console.log('Resend status:', resendCooldownRes.status);
  console.log('Resend body:', resendCooldownData);

  if (resendCooldownRes.status !== 429) throw new Error(`Expected 429 Too Many Requests, got ${resendCooldownRes.status}`);
  if (!resendCooldownData.retryAfter) throw new Error('Expected retryAfter seconds in response');
  console.log(`✔ Rate limiting verified: 429 received, retryAfter: ${resendCooldownData.retryAfter}s`);

  // 5. Test Invalid OTP verification
  console.log('\n[Test 4] Attempting verification with incorrect OTP');
  const invalidOtpRes = await fetch(`${BASE_URL}/auth/verify-otp`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: testEmail, otp: '000000' })
  });
  const invalidOtpData = await invalidOtpRes.json();

  console.log('Invalid OTP status:', invalidOtpRes.status, invalidOtpData.error);
  if (invalidOtpRes.status !== 400) throw new Error(`Expected 400 Bad Request, got ${invalidOtpRes.status}`);
  console.log('✔ Invalid OTP rejected with 400');

  // 6. Test Valid OTP verification
  console.log('\n[Test 5] Verifying with valid OTP generated by system');
  // Note: Since the test script runs in a separate process from the live server,
  // we set a known test OTP hash in DB to test the verify-otp endpoint
  const testOtp = '123456';
  const bcrypt = (await import('bcryptjs')).default;
  createdUser.otpHash = await bcrypt.hash(testOtp, 10);
  createdUser.otpExpiresAt = new Date(Date.now() + 10 * 60 * 1000);
  await createdUser.save();

  const validOtpRes = await fetch(`${BASE_URL}/auth/verify-otp`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: testEmail, otp: testOtp })
  });
  const validOtpData = await validOtpRes.json();

  console.log('Valid OTP status:', validOtpRes.status);
  console.log('Valid OTP body:', validOtpData);

  if (validOtpRes.status !== 200) throw new Error(`Expected 200 OK, got ${validOtpRes.status}`);
  if (!validOtpData.token) throw new Error('Expected JWT token after successful OTP verification');
  if (!validOtpData.user.isVerified) throw new Error('Expected user.isVerified: true in response');

  const verifiedUserInDb = await User.findOne({ email: testEmail });
  if (!verifiedUserInDb.isVerified) throw new Error('User.isVerified in DB should now be true');
  if (verifiedUserInDb.otpHash !== null) throw new Error('User.otpHash should be cleared after verification');
  if (verifiedUserInDb.otpExpiresAt !== null) throw new Error('User.otpExpiresAt should be cleared after verification');
  console.log('✔ Verification successful: isVerified=true, otpHash cleared, JWT token received');

  const authToken = validOtpData.token;

  // 7. Test Login After Verification
  console.log('\n[Test 6] Logging in as newly verified user');
  const verifiedLoginRes = await fetch(`${BASE_URL}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email: testEmail, password: testPassword })
  });
  const verifiedLoginData = await verifiedLoginRes.json();

  console.log('Verified login status:', verifiedLoginRes.status);
  if (verifiedLoginRes.status !== 200) throw new Error(`Expected 200 OK, got ${verifiedLoginRes.status}`);
  if (!verifiedLoginData.token) throw new Error('Expected JWT token');
  console.log('✔ Verified user logged in successfully with 200');

  // 8. Test Profile Validation (Feature 2)
  console.log('\n[Test 7] Testing profile validation rules');

  // 8a. Name too short
  const shortNameRes = await fetch(`${BASE_URL}/auth/profile`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`
    },
    body: JSON.stringify({ fullName: 'A', dob: '2000-01-01', educationLevel: 'Undergraduate' })
  });
  const shortNameData = await shortNameRes.json();
  console.log('Short name status:', shortNameRes.status, shortNameData.error);
  if (shortNameRes.status !== 400) throw new Error('Expected 400 for short name');

  // 8b. Numeric name
  const numericNameRes = await fetch(`${BASE_URL}/auth/profile`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`
    },
    body: JSON.stringify({ fullName: '12345678', dob: '2000-01-01', educationLevel: 'Undergraduate' })
  });
  const numericNameData = await numericNameRes.json();
  console.log('Numeric name status:', numericNameRes.status, numericNameData.error);
  if (numericNameRes.status !== 400) throw new Error('Expected 400 for numeric name');

  // 8c. Underage DOB (e.g. 5 years old)
  const fiveYearsAgo = new Date();
  fiveYearsAgo.setFullYear(fiveYearsAgo.getFullYear() - 5);
  const underageRes = await fetch(`${BASE_URL}/auth/profile`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`
    },
    body: JSON.stringify({
      fullName: 'Young Prodigy',
      dob: fiveYearsAgo.toISOString().slice(0, 10),
      educationLevel: 'Undergraduate'
    })
  });
  const underageData = await underageRes.json();
  console.log('Underage status:', underageRes.status, underageData.error);
  if (underageRes.status !== 400) throw new Error('Expected 400 for age < 13');

  // 8d. Invalid education level
  const invalidEduRes = await fetch(`${BASE_URL}/auth/profile`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`
    },
    body: JSON.stringify({
      fullName: 'Alex Scholar',
      dob: '2001-03-20',
      educationLevel: 'Kindergarten'
    })
  });
  const invalidEduData = await invalidEduRes.json();
  console.log('Invalid education status:', invalidEduRes.status, invalidEduData.error);
  if (invalidEduRes.status !== 400) throw new Error('Expected 400 for invalid education level');

  // 8e. Valid profile update
  console.log('\n[Test 8] Submitting valid profile update');
  const validProfileRes = await fetch(`${BASE_URL}/auth/profile`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`
    },
    body: JSON.stringify({
      fullName: 'Alex Scholar',
      dob: '2002-04-12',
      educationLevel: 'Undergraduate',
      institution: 'Carnegie Mellon University'
    })
  });
  const validProfileData = await validProfileRes.json();
  console.log('Valid profile status:', validProfileRes.status);
  console.log('Valid profile user:', validProfileData.user);
  if (validProfileRes.status !== 200) throw new Error(`Expected 200 for valid profile, got ${validProfileRes.status}`);
  if (validProfileData.user.fullName !== 'Alex Scholar') throw new Error('fullName mismatch');
  if (validProfileData.user.educationLevel !== 'Undergraduate') throw new Error('educationLevel mismatch');
  if (validProfileData.user.institution !== 'Carnegie Mellon University') throw new Error('institution mismatch');

  // 8f. Check GET /api/auth/me returns the extended profile fields
  console.log('\n[Test 9] Verifying GET /api/auth/me returns extended profile fields');
  const getMeRes = await fetch(`${BASE_URL}/auth/me`, {
    headers: {
      Authorization: `Bearer ${authToken}`
    }
  });
  const getMeData = await getMeRes.json();
  console.log('getMe status:', getMeRes.status);
  console.log('getMe profile:', {
    email: getMeData.user.email,
    isVerified: getMeData.user.isVerified,
    fullName: getMeData.user.fullName,
    dob: getMeData.user.dob,
    educationLevel: getMeData.user.educationLevel,
    institution: getMeData.user.institution
  });
  if (getMeRes.status !== 200) throw new Error('Expected 200 from getMe');
  if (getMeData.user.fullName !== 'Alex Scholar') throw new Error('fullName mismatch in getMe');
  if (getMeData.user.dob !== '2002-04-12') throw new Error('dob mismatch in getMe');
  if (getMeData.user.educationLevel !== 'Undergraduate') throw new Error('educationLevel mismatch in getMe');

  console.log('\n🎉 ALL OTP & PROFILE TESTS PASSED SUCCESSFULLY! 🎉\n');
  await mongoose.disconnect();
}

runTests().catch((err) => {
  console.error('Test execution failed:', err);
  process.exit(1);
});
